TASK_SEQS = {
    "CW0_0":[
        "hammer-v1",
        "hammer-v1",
    ],
    "CW0_1":[
        "hammer-v1",
        "push-wall-v1",
    ],
    "CW0_2":[
        "hammer-v1",
        "faucet-close-v1",
    ],
    "CW0_3":[
        "hammer-v1",
        "push-back-v1",
    ],
    "CW0_4":[
        "hammer-v1",
        "stick-pull-v1",
    ],
    "CW0_5":[
        "hammer-v1",
        "handle-press-side-v1",
    ],
    "CW0_6":[
        "hammer-v1",
        "push-v1",
    ],
    "CW0_7":[
        "hammer-v1",
        "shelf-place-v1",
    ],
    "CW0_8":[
        "hammer-v1",
        "window-close-v1",
    ],
    "CW0_9":[
        "hammer-v1",
        "peg-unplug-side-v1",
    ],
    "CW1_0":[
        "push-wall-v1",
        "hammer-v1",
    ],
    "CW1_1":[
        "push-wall-v1",
        "push-wall-v1",
    ],
    "CW1_2":[
        "push-wall-v1",
        "faucet-close-v1",
    ],
    "CW1_3":[
        "push-wall-v1",
        "push-back-v1",
    ],
    "CW1_4":[
        "push-wall-v1",
        "stick-pull-v1",
    ],
    "CW1_5":[
        "push-wall-v1",
        "handle-press-side-v1",
    ],
    "CW1_6":[
        "push-wall-v1",
        "push-v1",
    ],
    "CW1_7":[
        "push-wall-v1",
        "shelf-place-v1",
    ],
    "CW1_8":[
        "push-wall-v1",
        "window-close-v1",
    ],
    "CW1_9":[
        "push-wall-v1",
        "peg-unplug-side-v1",
    ],
    "CW2_0":[
        "faucet-close-v1",
        "hammer-v1",
    ],
    "CW2_1":[
        "faucet-close-v1",
        "push-wall-v1",
    ],
    "CW2_2":[
        "faucet-close-v1",
        "faucet-close-v1",
    ],
    "CW2_3":[
        "faucet-close-v1",
        "push-back-v1",
    ],
    "CW2_4":[
        "faucet-close-v1",
        "stick-pull-v1",
    ],
    "CW2_5":[
        "faucet-close-v1",
        "handle-press-side-v1",
    ],
    "CW2_6":[
        "faucet-close-v1",
        "push-v1",
    ],
    "CW2_7":[
        "faucet-close-v1",
        "shelf-place-v1",
    ],
    "CW2_8":[
        "faucet-close-v1",
        "window-close-v1",
    ],
    "CW2_9":[
        "faucet-close-v1",
        "peg-unplug-side-v1",
    ],
    "CW3_0":[
        "push-back-v1",
        "hammer-v1",
    ],
    "CW3_1":[
        "push-back-v1",
        "push-wall-v1",
    ],
    "CW3_2":[
        "push-back-v1",
        "faucet-close-v1",
    ],
    "CW3_3":[
        "push-back-v1",
        "push-back-v1",
    ],
    "CW3_4":[
        "push-back-v1",
        "stick-pull-v1",
    ],
    "CW3_5":[
        "push-back-v1",
        "handle-press-side-v1",
    ],
    "CW3_6":[
        "push-back-v1",
        "push-v1",
    ],
    "CW3_7":[
        "push-back-v1",
        "shelf-place-v1",
    ],
    "CW3_8":[
        "push-back-v1",
        "window-close-v1",
    ],
    "CW3_9":[
        "push-back-v1",
        "peg-unplug-side-v1",
    ],
    "CW4_0":[
        "stick-pull-v1",
        "hammer-v1",
    ],
    "CW4_1":[
        "stick-pull-v1",
        "push-wall-v1",
    ],
    "CW4_2":[
        "stick-pull-v1",
        "faucet-close-v1",
    ],
    "CW4_3":[
        "stick-pull-v1",
        "push-back-v1",
    ],
    "CW4_4":[
        "stick-pull-v1",
        "stick-pull-v1",
    ],
    "CW4_5":[
        "stick-pull-v1",
        "handle-press-side-v1",
    ],
    "CW4_6":[
        "stick-pull-v1",
        "push-v1",
    ],
    "CW4_7":[
        "stick-pull-v1",
        "shelf-place-v1",
    ],
    "CW4_8":[
        "stick-pull-v1",
        "window-close-v1",
    ],
    "CW4_9":[
        "stick-pull-v1",
        "peg-unplug-side-v1",
    ],
    "CW5_0":[
        "handle-press-side-v1",
        "hammer-v1",
    ],
    "CW5_1":[
        "handle-press-side-v1",
        "push-wall-v1",
    ],
    "CW5_2":[
        "handle-press-side-v1",
        "faucet-close-v1",
    ],
    "CW5_3":[
        "handle-press-side-v1",
        "push-back-v1",
    ],
    "CW5_4":[
        "handle-press-side-v1",
        "stick-pull-v1",
    ],
    "CW5_5":[
        "handle-press-side-v1",
        "handle-press-side-v1",
    ],
    "CW5_6":[
        "handle-press-side-v1",
        "push-v1",
    ],
    "CW5_7":[
        "handle-press-side-v1",
        "shelf-place-v1",
    ],
    "CW5_8":[
        "handle-press-side-v1",
        "window-close-v1",
    ],
    "CW5_9":[
        "handle-press-side-v1",
        "peg-unplug-side-v1",
    ],
    "CW6_0":[
        "push-v1",
        "hammer-v1",
    ],
    "CW6_1":[
        "push-v1",
        "push-wall-v1",
    ],
    "CW6_2":[
        "push-v1",
        "faucet-close-v1",
    ],
    "CW6_3":[
        "push-v1",
        "push-back-v1",
    ],
    "CW6_4":[
        "push-v1",
        "stick-pull-v1",
    ],
    "CW6_5":[
        "push-v1",
        "handle-press-side-v1",
    ],
    "CW6_6":[
        "push-v1",
        "push-v1",
    ],
    "CW6_7":[
        "push-v1",
        "shelf-place-v1",
    ],
    "CW6_8":[
        "push-v1",
        "window-close-v1",
    ],
    "CW6_9":[
        "push-v1",
        "peg-unplug-side-v1",
    ],
    "CW7_0":[
        "shelf-place-v1",
        "hammer-v1",
    ],
    "CW7_1":[
        "shelf-place-v1",
        "push-wall-v1",
    ],
    "CW7_2":[
        "shelf-place-v1",
        "faucet-close-v1",
    ],
    "CW7_3":[
        "shelf-place-v1",
        "push-back-v1",
    ],
    "CW7_4":[
        "shelf-place-v1",
        "stick-pull-v1",
    ],
    "CW7_5":[
        "shelf-place-v1",
        "handle-press-side-v1",
    ],
    "CW7_6":[
        "shelf-place-v1",
        "push-v1",
    ],
    "CW7_7":[
        "shelf-place-v1",
        "shelf-place-v1",
    ],
    "CW7_8":[
        "shelf-place-v1",
        "window-close-v1",
    ],
    "CW7_9":[
        "shelf-place-v1",
        "peg-unplug-side-v1",
    ],
    "CW8_0":[
        "window-close-v1",
        "hammer-v1",
    ],
    "CW8_1":[
        "window-close-v1",
        "push-wall-v1",
    ],
    "CW8_2":[
        "window-close-v1",
        "faucet-close-v1",
    ],
    "CW8_3":[
        "window-close-v1",
        "push-back-v1",
    ],
    "CW8_4":[
        "window-close-v1",
        "stick-pull-v1",
    ],
    "CW8_5":[
        "window-close-v1",
        "handle-press-side-v1",
    ],
    "CW8_6":[
        "window-close-v1",
        "push-v1",
    ],
    "CW8_7":[
        "window-close-v1",
        "shelf-place-v1",
    ],
    "CW8_8":[
        "window-close-v1",
        "window-close-v1",
    ],
    "CW8_9":[
        "window-close-v1",
        "peg-unplug-side-v1",
    ],
    "CW9_0":[
        "peg-unplug-side-v1",
        "hammer-v1",
    ],
    "CW9_1":[
        "peg-unplug-side-v1",
        "push-wall-v1",
    ],
    "CW9_2":[
        "peg-unplug-side-v1",
        "faucet-close-v1",
    ],
    "CW9_3":[
        "peg-unplug-side-v1",
        "push-back-v1",
    ],
    "CW9_4":[
        "peg-unplug-side-v1",
        "stick-pull-v1",
    ],
    "CW9_5":[
        "peg-unplug-side-v1",
        "handle-press-side-v1",
    ],
    "CW9_6":[
        "peg-unplug-side-v1",
        "push-v1",
    ],
    "CW9_7":[
        "peg-unplug-side-v1",
        "shelf-place-v1",
    ],
    "CW9_8":[
        "peg-unplug-side-v1",
        "window-close-v1",
    ],
    "CW9_9":[
        "peg-unplug-side-v1",
        "peg-unplug-side-v1",
    ],

    "CW3_0":[
        "push-v1",
        "window-close-v1",
        "hammer-v1",
    ],
    "CW3_1":[
        "hammer-v1",
        "window-close-v1",
        "faucet-close-v1",
    ],
    "CW3_2":[
        "stick-pull-v1",
        "push-back-v1",
        "push-wall-v1",
        ],
    "CW3_3":[
        "push-wall-v1",
        "shelf-place-v1",
        "push-back-v1",
        ],
    "CW3_4":[
        "faucet-close-v1",
        "shelf-place-v1",
        "push-back-v1",
        ],
    "CW3_5":[
        "stick-pull-v1",
        "peg-unplug-side-v1",
        "stick-pull-v1",
        ],
    "CW3_6":[
        "window-close-v1",
        "handle-press-side-v1",
        "peg-unplug-side-v1",
        ],
    "CW3_7":[
        "faucet-close-v1",
        "shelf-place-v1",
        "peg-unplug-side-v1",
        ],
    "CW10": [
        "hammer-v1",                # Hammer a screw on the wall. Randomize the hammer and the screw positions.
        "push-wall-v1",             # Bypass a wall and push a puck to a goal. Randomize puck and goal positions.
        "faucet-close-v1",          # Rotate the faucet clockwise. Randomize faucet positions.
        "push-back-v1",
        "stick-pull-v1",            # Grasp a stick and pull a box with the stick. Randomize stick positions.
        "handle-press-side-v1",     # Prehandle-press-sidess a handle down sideways. Randomize the handle positions
        "push-v1",                  # Push the puck to a goal. Randomize puck and goal positions.
        "shelf-place-v1",           # pick and place a puck onto a shelf. Randomize puck and shelf positions.
        "window-close-v1",          # Push and close a window. Randomize window positions
        "peg-unplug-side-v1",       # Unplug a peg sideways. Randomize peg positions.
    ],
}
TASK_SEQS["CW6_0"] = TASK_SEQS["CW3_0"] + TASK_SEQS["CW3_0"]
TASK_SEQS["CW6_1"] = TASK_SEQS["CW3_1"] + TASK_SEQS["CW3_1"]
TASK_SEQS["CW6_2"] = TASK_SEQS["CW3_2"] + TASK_SEQS["CW3_2"]
TASK_SEQS["CW6_3"] = TASK_SEQS["CW3_3"] + TASK_SEQS["CW3_3"]
TASK_SEQS["CW6_4"] = TASK_SEQS["CW3_4"] + TASK_SEQS["CW3_4"]
TASK_SEQS["CW6_5"] = TASK_SEQS["CW3_5"] + TASK_SEQS["CW3_5"]
TASK_SEQS["CW6_6"] = TASK_SEQS["CW3_6"] + TASK_SEQS["CW3_6"]
TASK_SEQS["CW6_7"] = TASK_SEQS["CW3_7"] + TASK_SEQS["CW3_7"]

TASK_SEQS["CW20"] = TASK_SEQS["CW10"] + TASK_SEQS["CW10"]
